version: '3.9'

services:
    api-dev:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api-dev
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - './app:/app'
        networks:
            - dev
        ports:
            - ${API_PORT:-80}:8000
        depends_on:
            - db-dev
        environment:
            PUID: 1001
            PGID: 1001
    queue-dev:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: queue-dev
        command: 'php artisan queue:work'
        networks:
            - dev
        depends_on:
            - db-dev
    db-dev:
        image: mysql:5.7
        container_name: db-dev
        environment:
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
            MYSQL_DATABASE: '${MYSQL_DATABASE}'
            MYSQL_USER: '${MYSQL_USERNAME}'
            MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'data-db:/var/lib/mysql'
        networks:
            - dev
        ports:
            - ${MYSQL_PORT:-3306}:3306
    redis-dev:
        image: 'redis:alpine'
        container_name: redis-dev
        ports:
            - ${REDIS_PORT:-6379}:6379
        volumes:
            - 'data-redis:/data'
        networks:
            - dev
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
          retries: 3
          timeout: 5s
    adminer-dev:
        image: adminer
        container_name: adminer-dev
        restart: always
        depends_on:
            - db-dev
        networks:
            - dev
        ports:
            - ${ADMINER_PORT:-8080}:8080
networks:
    dev:
        driver: bridge
volumes:
    data-db:
        driver: local
    data-redis:
        driver: local
